/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filemanagementsystem;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author kalilinux
 */
public class UploadedFiles extends javax.swing.JFrame {

    /**
     * Creates new form UploadedFiles
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public UploadedFiles() throws ClassNotFoundException, SQLException {
        initComponents();
        DatabaseConnection.DatabaseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        FramePanelRoot = new javax.swing.JPanel();
        DropONNPanel = new javax.swing.JPanel();
        dropOn = new javax.swing.JLabel();
        HintsPanel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ButtonsPanel = new javax.swing.JPanel();
        imageButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        documentsButton = new javax.swing.JButton();
        favouriteButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FramePanelRoot.setBackground(new java.awt.Color(17, 135, 254));

        DropONNPanel.setBackground(java.awt.Color.magenta);
        DropONNPanel.setFocusCycleRoot(true);
        DropONNPanel.setLayout(new java.awt.GridLayout());

        dropOn.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledShadow"));
        dropOn.setFont(new java.awt.Font("FreeSerif", 1, 24)); // NOI18N
        dropOn.setText("DropONN");
        DropONNPanel.add(dropOn);

        HintsPanel.setBackground(new java.awt.Color(21, 136, 251));
        HintsPanel.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jButton8.setText("jButton8");
        HintsPanel.add(jButton8);

        jButton9.setText("jButton9");
        HintsPanel.add(jButton9);

        jButton6.setText("jButton6");
        HintsPanel.add(jButton6);

        jButton7.setText("jButton7");
        HintsPanel.add(jButton7);

        ButtonsPanel.setBackground(new java.awt.Color(16, 113, 249));
        ButtonsPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        imageButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.shadow"));
        imageButton.setText("Images");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(imageButton);

        videoButton.setText("Videos");
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(videoButton);

        documentsButton.setText("Documents");
        ButtonsPanel.add(documentsButton);

        favouriteButton.setText("Favorite");
        ButtonsPanel.add(favouriteButton);

        javax.swing.GroupLayout FramePanelRootLayout = new javax.swing.GroupLayout(FramePanelRoot);
        FramePanelRoot.setLayout(FramePanelRootLayout);
        FramePanelRootLayout.setHorizontalGroup(
            FramePanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FramePanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HintsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(DropONNPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FramePanelRootLayout.setVerticalGroup(
            FramePanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FramePanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DropONNPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(HintsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jMenuBar1.setBackground(java.awt.Color.blue);
        jMenuBar1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("File");

        jMenuItem1.setText("Images");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Videos");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Documents");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Favourite");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("Select");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Select All");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Delete");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FramePanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        try {
            OwnFrame imagesFrame = new OwnFrame();
            imagesFrame.imageView();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UploadedFiles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imageButtonActionPerformed

    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
        try {
            VideoFrame videoframe = new VideoFrame();
        } catch (SQLException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(UploadedFiles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_videoButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            UploadedFiles imagesFiles = new UploadedFiles();
            imagesFiles.setVisible(true);

            // TODO add your handling code here:
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HomePageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadedFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadedFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadedFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadedFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UploadedFiles().setVisible(true);
                
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UploadedFiles.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JPanel DropONNPanel;
    private javax.swing.JPanel FramePanelRoot;
    private javax.swing.JPanel HintsPanel;
    private javax.swing.JButton documentsButton;
    private javax.swing.JLabel dropOn;
    private javax.swing.JButton favouriteButton;
    private javax.swing.JButton imageButton;
    private javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JButton videoButton;
    // End of variables declaration//GEN-END:variables
}
